create database customer_shopping_behavior; 
use customer_shopping_behavior;
select* from customer_shopping_behavior_clean; 

-- After preparring the data using python, low let us aswer these business questions: 

-- Q1. What is the total revenue generated by male customers compared to female customers?

select gender, sum(purchase_amount) as revenue
from customer_shopping_behavior_clean
group by gender; 

-- Q2. Which customers used a discount but still spent more than the overall average purchase amount?
select customer_id, purchase_amount
from customer_shopping_behavior_clean
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_shopping_behavior_clean); 
select* from customer_shopping_behavior_clean; 

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5
    item_purchased,
    round(avg(review_rating), 2) as average_product_rating
from customer_shopping_behavior_clean
group by item_purchased
order by avg(review_rating) desc;

-- Q4. Compare the average Purchase Amounts between Standard Shipping and Express Shipping.
select
    shipping_type,
    round(avg(purchase_amount),2) as average_purchase_amount
from customer_shopping_behavior_clean
group by shipping_type;

--Or only standard vs express shipping 
select shipping_type, round(AVG(purchase_amount),2)
from customer_shopping_behavior_clean
where shipping_type in ('Express', 'Standard') 
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare both the average spend 
-- and the total revenue between subscribers and non-subscribers.
select subscription_status, COUNT(customer_id)as total_customers, 
round(AVG(purchase_amount),2)as avg_spent, sum(purchase_amount) as total_revenue
from customer_shopping_behavior_clean
group by subscription_status;
select* from customer_shopping_behavior_clean;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) 
        / COUNT(*), 2
    ) AS discount_percentage
FROM customer_shopping_behavior_clean
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of customers in each segment.

WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_behavior_clean
)

SELECT 
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;
    
-- Q8. What are the top 3 most purchased products within each product category?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping_behavior_clean
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY item_rank,category;
select* from customer_shopping_behavior_clean; 

-- Q9. Are repeat buyers (more than 5 previous purchases) more likely to be subscribers?
select subscription_status,  
count (customer_id) as repeat_buyers
from customer_shopping_behavior_clean
where previous_purchases > 5
group by subscription_status; 

-- Q10. What is the revenue contribution (%) of each age group?

select age_group, SUM(purchase_amount) as total_revenue
from customer_shopping_behavior_clean
group by age_group
order by total_revenue desc; 
